workflows:
  version: 2
  publish:
    name: Publish to Google Play
    groups:
      - GooglePlay
    environment:
      vars:
        - GOOGLE_PLAY_JSON_KEY: $GOOGLE_PLAY_JSON_KEY

    scripts:
      - flutter build appbundle
      - cm publish
