workflows:
  build:
    name: Build and Test
    scripts:
      - flutter pub get

  publish:
    name: Publish to Google Play
    environment:
      vars:
        - GOOGLE_PLAY_JSON_KEY: $GOOGLE_PLAY_JSON_KEY

    scripts:
      - flutter build appbundle
      - cm publish
