name: foodfinder
description: Find the Dish you like!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.2

  # UI Libraries
  adaptive_theme: ^3.4.1
  intro_slider: ^4.2.1
  toastification: 1.0.2

  # Flutter Core
  http: ^1.1.0
  dart_secure: ^0.5.40
  shared_preferences: ^2.2.2

  # Onboarding
  introduction_screen: ^3.1.12

  # Other
  url_launcher: ^6.1.14



#run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"


dev_dependencies:

  #SaifAlmajd Packages
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.2
  local_auth: ^2.1.7

  #OTher
  lint: ^2.0.1
  google_mobile_ads: ^4.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400